version: "3.7"
services:
  ocr-web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
    # container_name: ocr-server
    # command: 
    #   - /bin/bash
    #   - -c
    #   - |
    #     /go/bin/ocrserver